# Dependencies
markdown: redcarpet
highlighter: rouge
  
# Permalinks
permalink: pretty
  
# Gems
gems: [jekyll-paginate, jekyll-gist]
paginate: 5
paginate_path: "page:num"

# Setup
tagline: 'gthio - blog'
baseurl: /

# My info
author:
  name: GThio
  github: gthio
  twitter: gthio
  url: https://github.com/gthio
  bio: Pragmatic software developer
