# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
  
# Gems
gems: [jekyll-paginate, jekyll-gist]
paginate: 5
paginate_path: "page:num"

# Setup
baseurl: /

# My info
author:
  name: GThio
  github: gthio
  twitter: gthio
  url: https://github.com/gthio
  bio: Pragmatic software developer
